import { Col, Row } from "antd";
import Head from "next/head";
import Logo from "../components/Logo";
import SearchForm from "../components/SearchForm";
import Toggle from "../components/Toggle";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>GitStats | Know your gitstats</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="preload"
          href="/fonts/Poppins-Medium.ttf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/Poppins-Regular.ttf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/Poppins-SemiBold.ttf"
          as="font"
          crossOrigin=""
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container__modeToggler}>
        <Toggle />
      </div>
      <Row align="middle" justify="center">
        <Col lg={12}>
          <Logo width={600} />
        </Col>
      </Row>
      <SearchForm />
    </div>
  );
}
